### ISSUE TITLE
Subscribe call gets rejected when _storageToken is empty string

### ISSUE THREAD

**Issue by simonerom** [iotexproject/pebble-prophecy#4]
Should _storageToken be allowed to be empty string (e.g. when no token is required)? 
Such tx where _accessToken == "" are currently getting reverted:

https://iotexscan.io/action/eb8487bd83b87c502e6db708ba5c207e12d4731f6d306a47355098370c5176c0

**Comment by raullenchai** [comment]
https://github.com/iotexproject/pebble-prophecy/commit/4307fa0226908d9a420be5b9cdbcfa082c8ce987
