### ISSUE TITLE
registerDevice does not allow to register with price = 0

### ISSUE THREAD

**Issue by simonerom** [iotexproject/pebble-prophecy#7]
"Free" data streams are not possible

**Comment by raullenchai** [comment]
https://github.com/iotexproject/pebble-prophecy/commit/0902763f3e06490177df3047d38f746cfa8c33bb

**Comment by raullenchai** [comment]
Do you need @dustinxie to help with deploy the new contract? @simonerom

**Comment by simonerom** [comment]
I can deploy it, I’ll send a PR to pebble firmware with the new address

**Comment by simonerom** [comment]
https://github.com/iotexproject/pebble-prophecy/pull/8
