### ISSUE TITLE
getDeviceOrderByID() seems to return invalid data when no order is available

### ISSUE THREAD

**Issue by simonerom** [iotexproject/pebble-prophecy#9]
**How to reproduce**
* Register a new device
* Call getDeviceOrderByID() before subscribe()

the result is something like:
```
ioctl contract test function io12rcmdvmd5htqces0p9jxr5d99gvzplty2dvc7a a.abi getDeviceOrderByID --with-arguments '{"_deviceId":"0x0000000000000000000000000000000000333532363536313030373834343135"}'  --endpoint api.iotex.one:443

return: 08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000c6e6f206f72646572207965740000000000000000000000000000000000000000
```

This return value seems to be invalid as it makes antenna-js to crash with an error right after the contract call is executed, but before returning:
```js
const orderInfo = await prophecyContract.methods.getDeviceOrderByID(idHex,{});
```
```
...
Error: Number can only safely store up to 53 bits
    at assert (/Users/xxx/Source/visualstudio/iotexdelegate.com/node_modules/bn.js/lib/bn.js:6:21)
    at BN.toNumber (/Users/xxx/Source/visualstudio/iotexdelegate.com/node_modules/bn.js/lib/bn.js:506:7)"
```

**Comment by raullenchai** [comment]
<img width="672" alt="Screen Shot 2020-12-04 at 6 13 25 PM" src="https://user-images.githubusercontent.com/989846/101230807-68519400-365c-11eb-9241-86163184b7e3.png">

We have a test to cover this so the contract should be good but getDeviceInfoByID returns too many args,  @ququzone is this a limit in antenna?

```
  function getDeviceInfoByID(
    bytes32 _deviceId
  ) public view returns (address, uint32, uint32, uint256, uint256, string memory, bytes memory, bytes memory) {

```

**Comment by raullenchai** [comment]
https://github.com/iotexproject/pebble-prophecy/commit/1ffc6e4c8d151548b986ca064414d421db61fb61
